name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Remove Previous App
      uses: JesseTG/rm@v1.0.0
      with:
        path: c:\tmp\PublishApp    
    - name: Remove Previous Launcher
      uses: JesseTG/rm@v1.0.0
      with:
        path: c:\tmp\PublishLauncher    

    - name: Build
      run: dotnet build --no-restore
    - name: Publish App
      run: dotnet publish Wabbajack\Wabbajack.csproj --runtime win10-x64 --configuration Release /p:Platform=x64 -o c:\tmp\PublishApp --self-contained
    - name: Publish Launcher
      run: dotnet publish Wabbajack.Launcher\Wabbajack.Launcher.csproj --runtime win10-x64 --configuration Release /p:Platform=x64 -o c:\tmp\PublishLauncher --self-contained
    - name: Sign App
      run: C:\"Program Files (x86)"\"Windows Kits"\10\bin\10.0.17763.0\x86\signtool.exe sign /sm c:\tmp\PublishApp\Wabbajack.exe
      shell: cmd
    - name: Sign Launcher
      run: C:\"Program Files (x86)"\"Windows Kits"\10\bin\10.0.17763.0\x86\signtool.exe sign /sm c:\tmp\PublishLauncher\Wabbajack.exe
      shell: cmd
    - name: Create Release Folder
      run: mkdir c:\wabbajack_releases\${{ github.event.inputs.version }}
    - name: Copy Launcher
      run: copy c:\tmp\PublishLauncher\Wabbajack.exe c:\wabbajack_releases\${{ github.event.inputs.version }}\Wabbajack.exe
    - name: Zip Release
      run: Compress-Archive -Path c:\tmp\PublishApp\* -DestinationPath c:\wabbajack_releases\${{ github.event.inputs.version }}\${{ github.event.inputs.version }}.zip

